name = "neon-hyperdrive"
main = "src/index.ts"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "NeonHyperdrive"
id = "e00ae1df7f614dd9858c1b3361011352"
